[package]
name = "interceptor-refactor"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
js-sys = "0.3.77"
reqwest = { version = "0.12.19" }
wasm-bindgen = "0.2.100"
wasm-bindgen-futures = "0.4.50"
web-sys = { version = "0.3.77", features = [
    "console",
    "Response",
    "Request",
    "Url",
    "RequestInit",
    "ResponseInit",
    "Headers",
    "ReadableStream",
    "ReadableStreamDefaultReader",
    "FormData",
    "Blob",
    "File",
    "UrlSearchParams",
] }


[dev-dependencies]
wasm-bindgen-test = "0.3.50"

[target.wasm32-unknown-unknown]
runner = 'wasm-bindgen-test-runner'
