[package]
name = "interceptor-wasm"
version = "0.1.7"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2.100"
wasm-bindgen-futures = "0.4.50"
web-sys = { version = "0.3.77", features = ["console", "Window", "Blob", "Event", "IdbTransactionMode",
    "IdbFactory", "IdbDatabase", "IdbTransaction", "IdbOpenDbRequest", "DomStringList", "IdbObjectStore",
    "IdbRequest", "IdbObjectStoreParameters", "DomException"] }
once_cell = "1.21.1"
reqwest = "0.12.15"
serde_json = "1.0.140"
serde-wasm-bindgen = "0.4"
bytes = "1.10.1"
js-sys = "0.3.77"

